# Generated by Django 4.1.4 on 2022-12-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name']},
        ),
    ]
